#' Print xml document created using spiritR
#' 
#' This function allows you to easily view the structure of the xml document
#' generated using the create_ctxml() function
#' 
#' @param ctxml The xml document generated by a call to create_ctxml()
#' 
#' @examples 
#' \dontrun{
#' print_ctxml(ctxml)
#' }
#' 
#' @export
#' @rdname print_ctxml
#' 
print_ctxml <- function(ctxml){
               cat(as.character(ctxml))
               }
